### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by agarzon48** [Geo504/Form-Proyect#1]
Muy bien ejecutado y buen responsive.

Sin embargo, solo los input radio tienen atributo name, que es el que utilizamos para rescatar el input del usuario. Por favor, introduce el atributo en el resto de inputs.

Como sugerencia, puedes comprobar que los campos apellido, ciudad, etc solo puedan contener letras con el atributo `pattern`

**Comment by Geo504** [comment]
Correcciones ya realizadas. Muchas gracias por las observaciones.

**Comment by agarzon48** [comment]
Perfecto!
